# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dglm": "00_dglm.ipynb"}

modules = ["dglm.py"]

doc_url = "https://lavinei.github.io/pybats_nbdev/"

git_url = "https://github.com/lavinei/pybats_nbdev/tree/master/"

def custom_doc_links(name): return None
